import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "./error";
import Providers from "./provider";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <header className="header">
            <p >Header</p>
          </header>
          <main className="m-6 content">
            <ToastContainer />
            <ErrorBoundary>
              {children}
            </ErrorBoundary>
          </main>
          <footer className="footer text-center" style={{backgroundColor:'ghostwhite', padding: '1rem'}}>
            <p >Footer</p>
          </footer>
        </Providers>
      </body>
    </html>
  );
}
