import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "./error";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor: 'lightblue', padding: '1rem'}}>
          <p className="header">Header</p>
        </header>
        <main className="m-6">
          <ErrorBoundary>
            {children}
          </ErrorBoundary>
        </main>
        <footer style={{backgroundColor:'ghostwhite', padding: '1rem'}}>
          <p className="footer">Footer</p>
        </footer>
      </body>
    </html>
  );
}
